# The configuration file for mgw
[server]
ip = "localhost"
port = "9095"
publicKeyPath = "/Users/viraj/go/src/github.com/VirajSalaka/product-microgateway/resources/certs/localhost.pem"
privateKeyPath = "/Users/viraj/go/src/github.com/VirajSalaka/product-microgateway/resources/certs/localhost.key"
username = "foo"
password = "bar"

[tls]
enabled = false
keystore = "security/wso2carbon.jks"
alias = "wso2carbon"
password = "wso2carbon"

[apis]
location = "resources/apis/"

[envoy]
listenerAddress = "0.0.0.0"
listenerPort = 10000
apiDefaultPort = 8080
clusterTimeoutInSeconds = 20

  