version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.16.0
    volumes:
      - ./resources/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
      - "9000:9000"
    links:
      - pilot
      - filterchain  
  pilot:
    image: vsalaka/mg-control-plane:3.2.1-SNAPSHOT
    volumes:  
      - ./resources/control-plane/certs:/home/wso2/certs
      - ./resources/control-plane/conf:/home/wso2/conf
    ports:
      - "18000:18000" 
  filterchain:
    image: vsalaka/mg-filter-chain:3.2.1-SNAPSHOT
    ports:
      - "8081:8081"   
