version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.14.1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
#    expose:
#      - "80"
#      - "8001"
    ports:
      - "10000:10000"
      - "9000:9000"
    links:
      - pilot
      - filterchain  
  pilot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:  
      - ./resources/apis/test2.yaml:/go/src/controlPlane/resources/apis/test2.yaml
    ports:
      - "18000:18000" 
  filterchain:
    build: 
      context: ./java-filter-chain
      dockerfile: dockerfile
    ports:
      - "8081:8081"         
  # zipkin:
  #   image: openzipkin/zipkin
  #   expose:
  #   - "9411"
  #   ports:
  #   - "9411:9411"
