version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.14.1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
#    expose:
#      - "80"
#      - "8001"
    ports:
      - "8080:10000"
      - "9901:9901"
  zipkin:
    image: openzipkin/zipkin
    expose:
    - "9411"
    ports:
    - "9411:9411"
