# The configuration file for mgw
[server]
ip = "0.0.0.0"
port = "9095"
publicKeyPath = "/home/wso2/certs/localhost.pem"
privateKeyPath = "/home/wso2/certs/localhost.key"
username = "foo"
password = "bar"

[envoy]
listenerAddress = "0.0.0.0"
listenerPort = 10000
clusterTimeoutInSeconds = 20
listenerTlsEnabled = true
listenerCertPath = "/home/wso2/certs/localhost.pem"
listenerKeyPath = "/home/wso2/certs/localhost.key"
