# The logging configuration file for mgw

######### root Level #############
logfile = "resources/logs/microgateway.log"
logLevel = "INFO"

[rotation]
MaxSize = 1    #megabytes
MaxBackups = 3
MaxAge =  28   #days
Compress = true

######### package Level #############
# LogLevels = "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"

[[pkg]]
name = "github.com/wso2/micro-gw/cmd/microgateway"
logLevel = "DEBG"

[[pkg]]
name = "microgateway"
logLevel = "INFO"

[[pkg]]
name = "oasparser"
logLevel = "DEBG"


[accessLogs]
logfile = "/tmp/envoy.access.log"
format = "[%START_TIME%] '%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%' %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% '%REQ(X-FORWARDED-FOR)%' '%REQ(USER-AGENT)%' '%REQ(X-REQUEST-ID)%' '%REQ(:AUTHORITY)%' '%UPSTREAM_HOST%'\n"


