version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.16.0
    volumes:
      - ./../../envoy.yaml:/etc/envoy/envoy.yaml
#    expose:
#      - "80"
#      - "8001"
    ports:
      - "10000:10000"
      - "9000:9000"
    links:
      - pilot
      - filterchain  
  pilot:
    build:
      context: ./../../
      dockerfile: docker/with-external-build/control-plane/Dockerfile
    volumes:  
      - ./../../resources/:/home/wso2/resources/
      - ./../../target/micro-gw-ubuntu:/home/wso2/micro-gw-ubuntu
    ports:
      - "18000:18000" 
  filterchain:
    build: 
      context: ./../../
      dockerfile: docker/with-external-build/filter-chain/Dockerfile
    volumes:
      - ./../../java-filter-chain/target:/home/wso2
    ports:
      - "8081:8081"         
  # zipkin:
  #   image: openzipkin/zipkin
  #   expose:
  #   - "9411"
  #   ports:
  #   - "9411:9411"
